apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
spec:
  tasks:
    - name: build-and-push
      taskRef:
        name: build-and-push
      params:
        - name: repo-url
          value: https://github.com/r-narayanan4/myapp.git
