apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations: {}
  generateName: build-and-deploy-execution-
  labels: {}
  namespace: default
spec:
  params:
    - name: gitUrl
      value: https://github.com/r-narayanan4/myapp.git
    - name: gitRevision
      value: HEAD
    - name: imageUrl
      value: rln410/demo-app
    - name: imageTag
      value: latest
    - name: pathToContext
      value: .
  pipelineRef:
    name: build-and-deploy-pipeline
  taskRunTemplate:
    serviceAccountName: pipeline-runner
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: git-source
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
        status: {}
