default: &default
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  username: postgres
  password: myrln
  host: postgres
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
